spring:
  application:
    name: fakebank

  datasource:
    url: jdbc:mysql://localhost:3306/anqing
#    username: v-fake-jaMCsYjkK
#    password: A1a-vMstysJSIBWe3FAe
#  profiles:
#    active: beta
